### ISSUE TITLE
cannot push my new changes in the notebook. fatal error. authentification mistake 

### ISSUE THREAD

**Issue by anjalisa** [Boyan-In-Christ/team10#1]
I have made changes in the notebook (statistical analysis part 1-3. Part 4 is still missing because of time reasons). Problem: I can not push it. An error occurs all the time, when I try to enter my password for github ("fatal error. authentification mistake), but the PW is correct. 

I will give it a try tomorrow or on Thursday morning.

**Comment by anjalisa** [comment]
ok guys, I found a solution for my problem and pushed my recent changes :)

**Comment by rogomichael** [comment]
Nice to hear that!

**Comment by Boyan-In-Christ** [comment]
Great job!

Boyan Zheng
Heidelberg
+49-176-6656-0932


rogomichael ***@***.***> 于2021年3月16日周二 上午10:08写道：

> Nice to hear that!
>
